backend:
  name: github                
  repo: Habakuk0/FinExactSolutions
  branch: main

site_url: https://finexactsolutions.co.ke

# Upload location inside the repo
media_folder: "client/src/assets/uploads"     # where files are stored in Git
public_folder: "/src/assets/uploads"          # public path the site uses

publish_mode: editorial_workflow

collections:
  - name: "resources"
    label: "Resources"
    folder: "src/content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

