backend:
  name: git-gateway
  branch: main   # or your deploy branch

media_folder: "client/public/uploads"
public_folder: "/uploads"

collections:
  - name: "resources"
    label: "Resources"
    folder: "client/src/content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

