backend:
  name: git-gateway
  branch: main

media_folder: "client/src/assets/uploads"
public_folder: "/src/assets/uploads"

collections:
  - name: "resources"
    label: "Resources"
    folder: "client/src/content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
